// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxjU5w1OtBec7RnOixCp5Dg2Q6Jyivo30',
    appId: '1:365140040804:web:e6886ba00b432d0a7dd371',
    messagingSenderId: '365140040804',
    projectId: 'med-reminder-372eb',
    authDomain: 'med-reminder-372eb.firebaseapp.com',
    storageBucket: 'med-reminder-372eb.appspot.com',
    measurementId: 'G-8GQYYK2C91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMynfvxctML-TbnQwxSz16B2485SX9pRc',
    appId: '1:365140040804:android:e0173150733c4cc87dd371',
    messagingSenderId: '365140040804',
    projectId: 'med-reminder-372eb',
    storageBucket: 'med-reminder-372eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvteOqHzyLefQ7tdrPUwyxWIJFO6wJlUA',
    appId: '1:365140040804:ios:63e1ec76d575a16a7dd371',
    messagingSenderId: '365140040804',
    projectId: 'med-reminder-372eb',
    storageBucket: 'med-reminder-372eb.appspot.com',
    androidClientId: '365140040804-1uqpu3knfpjq9st93h8k656euuaam2pv.apps.googleusercontent.com',
    iosClientId: '365140040804-6fm8grmqghdtnm5n8kt6hb4egu89f3h8.apps.googleusercontent.com',
    iosBundleId: 'com.medrem.medicinereminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvteOqHzyLefQ7tdrPUwyxWIJFO6wJlUA',
    appId: '1:365140040804:ios:63e1ec76d575a16a7dd371',
    messagingSenderId: '365140040804',
    projectId: 'med-reminder-372eb',
    storageBucket: 'med-reminder-372eb.appspot.com',
    androidClientId: '365140040804-1uqpu3knfpjq9st93h8k656euuaam2pv.apps.googleusercontent.com',
    iosClientId: '365140040804-6fm8grmqghdtnm5n8kt6hb4egu89f3h8.apps.googleusercontent.com',
    iosBundleId: 'com.medrem.medicinereminder',
  );
}
